# Generated by Django 3.0.2 on 2020-02-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ask',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
